apiVersion: v1
kind: Namespace
metadata:
  name: amqp-clients-test
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: tls
  namespace: amqp-clients-test
spec:
  replicas: 3
  image: pivotalrabbitmq/rabbitmq:main
  service:
    type: LoadBalancer
  # tls:
  #   secretName: tls-secret
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi
  rabbitmq:
    additionalPlugins:
      - rabbitmq_stream
      - rabbitmq_stream_management
    additionalConfig: |
      log.console = true
      log.console.level = debug