name: Trigger publish the client to nuget

on:
  release:
    types:
      # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
      - published

jobs:
  call-build-test:
    uses: ./.github/workflows/wf_build-and-test.yaml
  call-publish-nuget:
    uses: ./.github/workflows/wf_publish-nuget.yaml
    needs: call-build-test
    secrets: inherit
